spring.application.name=ias
server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# PostgreSQL
spring.r2dbc.url=${DB_URL:r2dbc:postgresql://localhost:5432/iasdb}
spring.r2dbc.username=${DB_USERNAME:ias}
spring.r2dbc.password=${DB_PASSWORD:ias}
spring.sql.init.mode=always

ias.rabbitmq.host=${RABBITMQ_HOST:localhost}
ias.rabbitmq.port=${RABBITMQ_PORT:5672}
ias.rabbitmq.username=${RABBITMQ_USERNAME:ias}
ias.rabbitmq.password=${RABBITMQ_PASSWORD:ias}
ias.rabbitmq.queue=transferencias.pendientes
